name: visionguard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - opencv
  - numpy
  - pillow
  - redis-py
  - sqlalchemy
  - uvicorn
  - fastapi
  - websockets
  - pydantic
  - python-dotenv
  - aiofiles
  - pip
  - pip:
      - anthropic==0.7.8
      - python-jose[cryptography]==3.3.0
      - passlib[bcrypt]==1.7.4
      - alembic==1.12.1
      - aiosqlite==0.19.0
      - python-multipart==0.0.6
      - jinja2==3.1.2
      - pydantic-settings==2.1.0
